micronaut:
  application:
    name: pixKeymanagerGrpc

datasources:
  default:
    url: ${JDBC_DB:`jdbc:postgresql://localhost:5432/pix`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:cocacola}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: true

client:
  itau:
    erp:
      url: ${ITAU_ERP_URL:`http://localhost:9091/api/v1/clientes`}
  bacen:
    url: ${BACEN_URL:`http://localhost:8082/api/v1/pix/keys`}

